### ISSUE TITLE
Division by Zero Calculating Results Stats

### ISSUE THREAD

**Issue by dennislabajo** [dennislabajo/pre-trained-image-classifier#14]
Running the check images program via `sh run_models_batch_uploaded.sh` after new images have been uploaded results in the error below:

```
2019-01-04 13:58:32,496 [calculates_results_stats]  ERROR: Error calculating statistics percentage - division by zero
2019-01-04 13:58:32,497 [__main__]  ERROR: Abnormal exit due to division by zero error
Traceback (most recent call last):
  File "check_images.py", line 93, in main
    results_stats = calculates_results_stats(results)
  File "/work/dvl/udcy/ai-nd/pre-trained-image-classifier/src/calculates_results_stats.py", line 83, in calculates_results_stats
    calculates_results_stats_percentage(results_stats_dic)
  File "/work/dvl/udcy/ai-nd/pre-trained-image-classifier/src/calculates_results_stats.py", line 190, in calculates_results_stats_percentage
    results_stats_dic['n_dogs_img']) * 100
ZeroDivisionError: division by zero
```

**Comment by dennislabajo** [comment]
Code fixed and merged.
